### ISSUE TITLE
Bluetooth not suported 

### ISSUE THREAD

**Issue by dioscarr** [Apt3kStudio/Phone#6]
Bluetooth not suported on emulator. We need to configure a gateway between visual studio and external devices. This needs to be research.

**Comment by nvasquedr** [comment]
https://docs.microsoft.com/en-us/xamarin/android/wear/deploy-test/debug-on-device

**Comment by dioscarr** [comment]
### Companion Applications

Another strategy is to create a complete application that runs natively on the wearable device and pairs with a companion handheld app. A good example of this approach is the Quiz sample app, which demonstrates how to create a quiz that runs on a handheld device and asks quiz questions on the wearable device.

**Comment by jagomez16** [comment]
Wearable Notifications

The simplest way to support Android Wear is to take advantage of the shared nature of notifications between the handheld and the wearable device. By using the support v4 notification API and the WearableExtender class (available in the Xamarin Android Support Library), you can tap into the native features of the platform, like inbox style cards or voice input. The RecipeAssistant sample provides example code that demonstrates how to send a list of notifications to an Android Wear device.

**Comment by jagomez16** [comment]
Android Wear Basics

Android Wear has a user interface paradigm that differs from that of Android handheld apps. The first wave of Wear apps were designed to extend a companion handheld app in some way, but beginning with Android Wear 2.0, Wear apps can be used standalone. When you deploy a Wear app, it is packaged with a companion handheld app. Because most Wear apps depend upon a handheld companion app, they need some way to communicate with handheld apps. The following sections describe these usage scenarios and outline the essential Android Wear features.
